In [12]:
import cv2
img = cv2.imread('call.png')
# resized = cv2.resize(img, (10, 10), cv2.INTER_LINEAR)
print (img)

[[[177 177 177]
  [218 218 218]
  [211 211 211]
  ...
  [212 212 212]
  [212 212 212]
  [212 212 212]]

 [[218 218 218]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[211 211 211]
  [255 255 255]
  [251 251 251]
  ...
  [253 253 253]
  [253 253 253]
  [253 253 253]]

 ...

 [[212 212 212]
  [255 255 255]
  [253 253 253]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[212 212 212]
  [255 255 255]
  [253 253 253]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[212 212 212]
  [255 255 255]
  [253 253 253]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [13]:
img = img.transpose(2,0,1).reshape(3,-1)

In [14]:
img

array([[177, 218, 211, ..., 255, 255, 255],
       [177, 218, 211, ..., 255, 255, 255],
       [177, 218, 211, ..., 255, 255, 255]], dtype=uint8)

In [15]:
img = img[0]

In [16]:
img

array([177, 218, 211, 212, 212, 212, 212, 212, 212, 212, 212, 212, 212,
       212, 212, 212, 212, 212, 212, 212, 212, 212, 212, 212, 212, 212,
       212, 212, 218, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
       255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
       255, 255, 255, 255, 211, 255, 251, 253, 253, 253, 253, 253, 253,
       253, 253, 253, 253, 253, 253, 253, 253, 253, 253, 253, 253, 253,
       253, 253, 253, 253, 253, 253, 212, 255, 253, 255, 255, 255, 255,
       255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
       255, 255, 255, 255, 255, 255, 255, 255, 212, 255, 253, 255, 255,
       255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
       255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 212, 255, 253,
       255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
       255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 212,
       255, 253, 254, 255, 254, 252, 251, 252, 252, 252, 252, 25

In [17]:
w, h = 28, 28;
mat = [[0 for x in range(w)] for y in range(h)] 


In [18]:
c=0
for i in range(28):
    for j in range(28):
        if(img[c] <= 127):
            img[c] = 0
        else:
            img[c] = 1
        mat[i][j] = img[c]
        print(mat[i][j], end= '')
        c+=1
    print("")

1111111111111111111111111111
1111111111111111111111111111
1111111111111111111111111111
1111111111111111111111111111
1111111111111111111111111111
1111111111111111111111111111
1111111111111111111111111111
1111111111111111111111111111
1111111111111111111111111111
1111110000000000000000111111
1111110000000000000000111111
1111110000000000000000111111
1111110000000000000000111111
1111110000000000000000111111
1111110000000000000000111111
1111111010001000010001111111
1111111111111100111111111111
1111111111111101111111111111
1111111111111101111111111111
1111111111111111111111111111
1111111111111111111111111111
1111111111111111111111111111
1111111111111111111111111111
1111111111111111111111111111
1111111111111111111111111111
1111111111111111111111111111
1111111111111111111111111111
1111111111111111111111111111


In [19]:
mat[19][17] = 1

In [20]:
for i in range(28):
    for j in range(28):
        print(mat[i][j], end= '')
    print("")

1111111111111111111111111111
1111111111111111111111111111
1111111111111111111111111111
1111111111111111111111111111
1111111111111111111111111111
1111111111111111111111111111
1111111111111111111111111111
1111111111111111111111111111
1111111111111111111111111111
1111110000000000000000111111
1111110000000000000000111111
1111110000000000000000111111
1111110000000000000000111111
1111110000000000000000111111
1111110000000000000000111111
1111111010001000010001111111
1111111111111100111111111111
1111111111111101111111111111
1111111111111101111111111111
1111111111111111111111111111
1111111111111111111111111111
1111111111111111111111111111
1111111111111111111111111111
1111111111111111111111111111
1111111111111111111111111111
1111111111111111111111111111
1111111111111111111111111111
1111111111111111111111111111


In [21]:
p = 0
for i in range(28):
    for j in range(28):
        if (mat[i][j] == 0):
            if(mat[i-1][j] == 1):
                p+=1
                mat[i-1][j] = 2
            if(mat[i][j-1] == 1):
                p+=1
                mat[i][j-1] = 2
            if(mat[i][j+1] == 1):
                p+=1
                mat[i][j+1] = 2
            if(mat[i+1][j] == 1):
                p+=1
                mat[i+1][j] = 2
print(p)

47


In [22]:
for i in range(28):
    for j in range(28):
        print(mat[i][j], end= '')
    print("")

1111111111111111111111111111
1111111111111111111111111111
1111111111111111111111111111
1111111111111111111111111111
1111111111111111111111111111
1111111111111111111111111111
1111111111111111111111111111
1111111111111111111111111111
1111112222222222222222111111
1111120000000000000000211111
1111120000000000000000211111
1111120000000000000000211111
1111120000000000000000211111
1111120000000000000000211111
1111120000000000000000211111
1111112020002000020002111111
1111111212221200212221111111
1111111111111202111111111111
1111111111111202111111111111
1111111111111121111111111111
1111111111111111111111111111
1111111111111111111111111111
1111111111111111111111111111
1111111111111111111111111111
1111111111111111111111111111
1111111111111111111111111111
1111111111111111111111111111
1111111111111111111111111111
